# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps: 
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'C:\Workspace\TimeProject\front'
